---
title: "Yogurt_Data-Explore"
author: "Paul Foley"
date: "7/10/2017"
output: html_document
---

## Load Libraries
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(GGally)
library(reshape2)
```

## Load Yogurt Data
```{r}
getwd()
list.files()
yogurt <- read.csv('yogurt.csv')
str(yogurt)
names(yogurt)

yogurt$id <- factor(yogurt$id)
str(yogurt)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Yogurt Histogram
```{r}
ggplot(data = yogurt,
       aes(x = price)) +
  geom_histogram(binwidth = 1)
```

## Number of Purchases
```{r}
yogurt <- transform(yogurt, all_purchases = strawberry + blueberry + pina.colada + plain + mixed.berry)
```

## Prices Over Time
```{r}
ggplot(data = yogurt,
       aes(x = time, y = price)) +
  geom_jitter(alpha = 1/4,
              shape = 21)
```

## Looking at Samples of Households
```{r}
set.seed(3000)
sample_ids <- sample(levels(yogurt$id), 16)

ggplot(data = subset(yogurt, id %in% sample_ids),
       aes(x = time, y = price)) +
  facet_wrap(~ id) +
  geom_line() +
  geom_point(pch = 1,
             aes(size = all_purchases))
ggsave('YogurtPlotGraphs.png')
```


